export const GET_ALL_TODOS_REQUEST = 'GET_ALL_TODOS_REQUEST';
export const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCCESS';

export const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST';
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';

export const TODO_REQUEST_FAILED = 'TODO_REQUEST_FAILED';

export const SWITCH_UPDATE_WINDOW = 'SWITCH_UPDATE_WINDOW'

export const SWITCH_SIGNIN_WINDOW = 'SWITCH_SIGNIN_WINDOW'

